% This function read the cortex location, target locations (i.e., Mask file generated by the physcial therapist or
% neuroscientist), and target currents during a window.
function [cortexL,targetL,targetC]=find_target_PC4_all(inv_file_name,MaskFile,TimePoints,plotCort)

[cortexL,Lcount,LNR]=read_Curry_file3(inv_file_name,'LOCATION',0,0);
load (MaskFile)
contrib=[];
fpos=0;
for i=1:TimePoints
    if i==1
        [contrib_tmp,Ccount,CNR]=read_Curry_file4_AC(inv_file_name,'STRENGTH',1,0);
    elseif i==TimePoints
        [contrib_tmp,Ccount,CNR]=read_Curry_file4_AC(inv_file_name,'STRENGTH',1,1);
    else
        [contrib_tmp,Ccount,CNR]=read_Curry_file4_AC(inv_file_name,'STRENGTH',0,1);
    end
    contrib=[contrib,contrib_tmp];
end

%--------Select the points inside the edge---------------
Tind=[];
[n]=size(ROI_ind);
[m,tmp]=size(cortexL);


for i_location =1:8
    loc_ind_tmp=find(ROI_ind_group2==i_location);
    targetL{i_location,1}=cortexL(ROI_ind(loc_ind_tmp),:);
    targetC{i_location,1}=contrib(ROI_ind(loc_ind_tmp),:);
end
i_color = {'r+','m+','c+','g+','y+','g+','c+','y+'};
if plotCort
	figure 
	plot3(cortexL(:,1),cortexL(:,2),cortexL(:,3),'b.', 'MarkerSize',3);
	hold on
    for i_location =1:8
        tmp_targetL = targetL{i_location};
        plot3(squeeze(tmp_targetL(:,1)),tmp_targetL(:,2),tmp_targetL(:,3),i_color{i_location},'MarkerSize',5);
    end
end