% This function read the cortex location, target locations (i.e., Mask file generated by the physcial therapist or
% neuroscientist), and target currents during a window.
function [cortexL,targetL,targetC]=find_target_PC4_old(inv_file_name,MaskFile,TimePoints,plotCort)
%cortex_ind: 0-right, 1-left, 2-all

[cortexL,Lcount,LNR]=read_Curry_file3(inv_file_name,'LOCATION',0,0);
load (MaskFile)
contrib=[];
fpos=0;
for i=1:TimePoints
    if i==1
        [contrib_tmp,Ccount,CNR]=read_Curry_file4_AC(inv_file_name,'STRENGTH',1,0);
    elseif i==TimePoints
        [contrib_tmp,Ccount,CNR]=read_Curry_file4_AC(inv_file_name,'STRENGTH',1,1);
    else
        [contrib_tmp,Ccount,CNR]=read_Curry_file4_AC(inv_file_name,'STRENGTH',0,1);
    end
    contrib=[contrib,contrib_tmp];
end

%--------Select the points inside the edge---------------
Tind=[];
[n]=size(ROI_ind);
[m,tmp]=size(cortexL);

% ROI_ind=ROI_ind(find(ROI_ind_group==cortex_ind));
targetL=cortexL(ROI_ind,:);
targetC=contrib(ROI_ind,:);
if plotCort
	figure 
	plot3(cortexL(:,1),cortexL(:,2),cortexL(:,3),'b.', 'MarkerSize',3);
	hold on
	plot3(targetL(:,1),targetL(:,2),targetL(:,3),'m+','MarkerSize',5);
end