% This function read the cortex location, target locations (i.e., Mask file generated by the physcial therapist or
% neuroscientist), and target currents during a window.
function [cortexL,targetL,targetC]=read_ccd_simp(inv_file_name,TimePoints,plotCort,target_location)

[cortexL,Lcount,LNR]=read_Curry_file3(inv_file_name,'LOCATION',0,0);
% load (MaskFile)
contrib=[];
fpos=0;
for i=1:TimePoints
    if i==1
        [contrib_tmp,Ccount,CNR]=read_Curry_file4_AC(inv_file_name,'STRENGTH',1,0);
    elseif i==TimePoints
        [contrib_tmp,Ccount,CNR]=read_Curry_file4_AC(inv_file_name,'STRENGTH',1,1);
    else
        [contrib_tmp,Ccount,CNR]=read_Curry_file4_AC(inv_file_name,'STRENGTH',0,1);
    end
    contrib=[contrib,contrib_tmp];
end

%--------Select the points inside the edge---------------
Tind=[];
% [n]=size(ROI_ind);
[m,tmp]=size(cortexL);


for i_location =1:size(target_location,1)
    [min_d,loc_ind_tmp]=min( sum ((cortexL-repmat(target_location(i_location,:), 9494,1) )'.^2).^0.5);
    targetL{i_location,1}=cortexL(loc_ind_tmp,:);
    targetC{i_location,1}=contrib(loc_ind_tmp,:);
end
% i_color = {'r+','m+','c+','g+','y+','g+','c+','y+'};
% if plotCort
% 	figure 
% 	plot3(cortexL(:,1),cortexL(:,2),cortexL(:,3),'b.', 'MarkerSize',3);
% 	hold on
%     for i_location =1:length(target_location)
%         tmp_targetL = targetL{i_location};
%         plot3(squeeze(tmp_targetL(:,1)),tmp_targetL(:,2),tmp_targetL(:,3),i_color{i_location},'MarkerSize',5);
%     end
% end